name: kepu
description: Movie,Show,Game and Music tracking app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  equatable: ^2.0.5
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: any
  dio: any
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4
  google_sign_in: ^5.4.2
  provider: ^6.0.5
  font_awesome_flutter: ^10.3.0
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  unicons: ^2.1.0
  cached_network_image: ^3.2.3
  go_router: ^8.2.0
  url_launcher: ^6.1.8
  lottie: ^2.3.2
  cloud_firestore: ^4.7.1
  intl: ^0.18.1
  google_fonts: ^4.0.4
  fluttericon: ^2.0.0
  path: ^1.8.3
  sqflite: ^2.3.0
  gap: ^3.0.1
  firebase_database: ^10.3.4
  get: ^4.6.5
  email_validator: ^2.1.17
  shared_preferences: ^2.2.0
  sign_in_with_apple: ^5.0.0
  flutter_svg: any
  animated_bottom_navigation_bar: ^1.2.0
  material_design_icons_flutter: ^7.0.7296
  msh_checkbox: ^1.1.1
  uuid: ^3.0.6
  flutter_fortune_wheel: ^1.3.0
  rxdart: ^0.27.3

  audio_service: ^0.18.10
  audio_video_progress_bar: ^1.0.1
  dart_des: ^1.0.2
  eva_icons_flutter: ^3.1.0
  get_it: ^7.6.0
  iconsax: ^0.0.8
  just_audio: ^0.9.35
  sliding_up_panel: ^2.0.0+1
  logging: any
  duration_picker: ^1.1.1
  flutter_displaymode: ^0.6.0
  flutter_swipe_action_cell: ^3.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_colorpicker: ^1.0.3
  dropdown_button2: ^2.3.9
  dynamic_color: ^1.6.5
  flutter_lyric: ^2.0.4+6
  flip_card: ^0.7.0
  permission_handler: ^10.4.1
  flutter_progress_status: ^0.0.3
  path_provider: ^2.0.15
  youtube_explode_dart: ^2.0.2
  auto_size_text: ^3.0.0
  skeletons: ^0.0.3
  country_picker: ^2.0.20
  audio_tagger:
    git:
      url: https://github.com/SongTube/audio_tagger
      ref: main
  just_audio_mpv: ^0.1.7
  audiotags: ^1.2.1
  bitsdojo_window: ^0.1.5
  change_app_package_name: ^1.1.0
  titlebar_buttons: ^1.0.0

  auto_route: ^7.8.4

  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  mocktail: ^0.3.0
  bloc_test: ^9.1.0
  floor: ^1.4.1
  floor_generator: ^1.3.0
  internet_connection_checker: ^1.0.0+1
  retrofit: ^4.0.1
  logger: ^1.1.0
  carbon_icons: ^0.0.1+2
  share_plus: ^6.3.1
  fluttertoast: ^8.2.1
  flutter_spinkit: ^5.1.0
  flutter_native_splash: ^2.2.19
  mockito: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  image_path_android: "assets/AppIcon.png"
  adaptive_icon_background: "assets/launcher_icon/background.png"
  adaptive_icon_foreground: "assets/launcher_icon/foreground.png"


flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/
    - assets/
    - assets/images/
    - assets/icons/
    - assets/page-1/images/
    - assets/pick.png
    - assets/pick1.png
    - assets/pick2.png
    - assets/wheel.png
    - assets/wheel1.png
    - assets/wheel2.png
    - assets/BottomNav/Activecottage_FILL0_wght400_GRAD0_opsz24 2.png
    - assets/BottomNav/Activectodo_FILL0_wght400_GRAD0_opsz24 1.png
    - assets/BottomNav/Activeperson_FILL0_wght400_GRAD0_opsz24 1.png
    - assets/BottomNav/Activetoys_fan_FILL0_wght400_GRAD0_opsz24 1.png
    - assets/BottomNav/add.png
    - assets/BottomNav/appActive.png
    - assets/BottomNav/cottage_FILL0_wght400_GRAD0_opsz24 2.png
    - assets/BottomNav/person_FILL0_wght400_GRAD0_opsz24 1.png
    - assets/BottomNav/todo_FILL0_wght400_GRAD0_opsz24 1.png
    - assets/BottomNav/toys_fan_FILL0_wght400_GRAD0_opsz24 1.png
    - assets/launcher_icon/mipmap-hdpi/ic_launcher.png
    - assets/launcher_icon/mipmap-mdpi/ic_launcher.png
    - assets/launcher_icon/mipmap-xhdpi/ic_launcher.png
    - assets/launcher_icon/mipmap-xxhdpi/ic_launcher.png
    - assets/launcher_icon/mipmap-xxxhdpi/ic_launcher.png
    - assets/launcher_icon/foreground.png
flutter_intl:
  enabled: true


